version: '3.8'

services:
  backend:
    container_name: cte_backend
    image: docker.pkg.github.com/yaroslaww-1/cte/cte-backend:latest
    ports: 
      - 5001:5001
    environment:
      - BACKEND_HOST
      - BACKEND_PORT
      - BACKEND_DATABASE_URL
      - BACKEND_JWT_SECRET
      - BACKEND_MAILER_EMAIL_ADDRESS
      - BACKEND_MAILER_EMAIL_PASSWORD
      - BACKEND_FRONTEND_APP_URL
      - BACKEND_COOKIE_DOMAIN
      - BACKEND_CLIENT_ID
      - BACKEND_CLIENT_SECRET
    restart: always
    networks:
      - cte-network

  frontend:
    container_name: cte_frontend
    image: docker.pkg.github.com/yaroslaww-1/cte/cte-frontend:latest
    ports:
      - 80:80
    restart: always
    networks:
      - cte-network

networks:
  cte-network: