version: '3.6'

services:
  backend:
    container_name: cte_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports: 
      - "5001:5001"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${BACKEND_PORT}
      HOST: ${BACKEND_HOST}
    networks: 
      - cte_network
    restart: always

  frontend:
    container_name: cte_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"

networks:
  cte_network:
    driver: bridge
    