version: '3.8'

services:
  backend:
    container_name: cte_backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports: 
      - 5001:5001
    env_file:
      - ./backend/.env
    environment: 
      - FRONTEND_APP_URL=http://localhost
    restart: always
    networks:
      - cte-network
    # Please see https://stackoverflow.com/questions/31249112/allow-docker-container-to-connect-to-a-local-host-postgres-database
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  frontend:
    container_name: cte_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
      - 80:80
    env_file:
      - ./frontend/.env
    networks:
      - cte-network

networks:
  cte-network: