version: '3.6'

services:
  backend:
    container_name: cte_backend
    image: docker.pkg.github.com/yaroslaww-1/cte/cte-backend:latest
    ports: 
      - "5001:5001"
    depends_on: 
      - 'db'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${BACKEND_PORT}
      HOST: ${BACKEND_HOST}
    networks: 
      - cte_network
    restart: always
  

  frontend:
    container_name: cte_frontend
    image: docker.pkg.github.com/yaroslaww-1/cte/cte-frontend:latest
    ports:
      - "80:80"

networks:
  cte_network:
    driver: bridge

volumes:
  postgres: