version: '3.6'

services:
  backend:
    container_name: cte_backend
    build:
      network: host
      context: .
      dockerfile: ./backend/Dockerfile
    ports: 
      - "5001:5001"
      - "5432:5432"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${BACKEND_PORT}
      HOST: ${BACKEND_HOST}
    network_mode: host
    restart: always

  frontend:
    container_name: cte_frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:80"