version: '3.6'

services:
  backend:
    container_name: cte_backend
    image: docker.pkg.github.com/yaroslaww-1/cte/cte-backend:latest
    ports: 
      - "5001:5001"
      - "5432:5432"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${BACKEND_PORT}
      HOST: ${BACKEND_HOST}
    network_mode: host
    restart: always

  frontend:
    container_name: cte_frontend
    image: docker.pkg.github.com/yaroslaww-1/cte/cte-frontend:latest
    ports:
      - "80:80"