// 12 hours
const EMAIL_CONFIRM_TOKEN_EXPIRES_IN_MILLISECONDS = 12 * 60 * 50 * 1000;
const EMAIL_CONFIRM_TOKEN_TYPE = 'email-confirm';

export { EMAIL_CONFIRM_TOKEN_EXPIRES_IN_MILLISECONDS, EMAIL_CONFIRM_TOKEN_TYPE };
