// 60 days
const REFRESH_TOKEN_EXPIRES_IN_MILLISECONDS = 60 * 24 * 60 * 60 * 1000;
const MAX_REFRESH_SESSIONS_COUNT = 5;

// 30 minutes
const ACCESS_TOKEN_EXPIRES_IN_MILLISECONDS = 30 * 60 * 1000;
const ACCESS_TOKEN_TYPE = 'access';

export {
	REFRESH_TOKEN_EXPIRES_IN_MILLISECONDS,
	MAX_REFRESH_SESSIONS_COUNT,
	ACCESS_TOKEN_TYPE,
	ACCESS_TOKEN_EXPIRES_IN_MILLISECONDS,
};
