// 60 days
const REFRESH_TOKEN_LIFETIME_IN_SECONDS = 60 * 24 * 60 * 60;
const MAX_REFRESH_SESSIONS_COUNT = 5;

// 30 minutes
const ACCESS_TOKEN_LIFETIME_IN_SECONDS = 30 * 60;
const ACCESS_TOKEN_TYPE = 'access';

export {
  REFRESH_TOKEN_LIFETIME_IN_SECONDS,
  MAX_REFRESH_SESSIONS_COUNT,
  ACCESS_TOKEN_TYPE,
  ACCESS_TOKEN_LIFETIME_IN_SECONDS,
};
