name: lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: yarn install
    - name: lint
      run: yarn lint
    - name: test
      run: echo "Hello world"