name: lint

on:
  pull_request:

jobs:
  setup-node-modules:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      id: node-modules-cache
      with:
        path: 'node_modules'
        key: node_modules-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          node_modules-
    - name: install dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: yarn install

  lint:
    needs: setup-node-modules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: load node_modules
      uses: actions/cache@v2
      with:
        path: 'node_modules'
        key: node_modules-${{ hashFiles('yarn.lock') }}
    - name: lint
      run: yarn lint
      