name: build

on:
  pull_request:
    branches: 
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          PauseChamp! Pull request is created! :eyes:
          Url: https://github.com/Yaroslaww-1/cte/pull/${{ github.event.number }}